spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?useSSL=false
    username: root
    password: root 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect 
    generate-ddl: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-zone-a:4002/eureka